### ISSUE TITLE
Errors 10.0.2 Evoker

### ISSUE THREAD

**Issue by Mithras2801** [Tercioo/Details-Framework#10]
3x LibDFramework-1.0/embeds.xml:2 Error loading LibDFramework-1.0/Libs/LibStub-1.0.2-70000/LibStub.lua

3x LibDFramework-1.0/embeds.xml:3 Error loading LibDFramework-1.0/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua

3x LibDFramework-1.0/embeds.xml:4 Couldn't open LibDFramework-1.0/Libs/LibSharedMedia-3.0-8020003/lib.xml

3x LibDFramework-1.0/embeds.xml:5 Couldn't open LibDFramework-1.0/Libs/AceGUI-3.0-41/AceGUI-3.0.xml

3x LibDFramework-1.0/embeds.xml:6 Couldn't open LibDFramework-1.0/Libs/AceDBOptions-3.0-15/AceDBOptions-3.0.xml

3x LibDFramework-1.0/embeds.xml:7 Couldn't open LibDFramework-1.0/Libs/AceLocale-3.0-6/AceLocale-3.0.xml

3x LibDFramework-1.0/embeds.xml:8 Couldn't open LibDFramework-1.0/Libs/AceAddon-3.0-13/AceAddon-3.0.xml

3x LibDFramework-1.0/embeds.xml:9 Couldn't open LibDFramework-1.0/Libs/AceDB-3.0-27/AceDB-3.0.xml

3x LibDFramework-1.0/embeds.xml:10 Couldn't open LibDFramework-1.0/Libs/AceTimer-3.0-17/AceTimer-3.0.xml

3x LibDFramework-1.0/embeds.xml:11 Couldn't open LibDFramework-1.0/Libs/AceConfig-3.0-3/AceConfig-3.0.xm

![WoWScrnShot_112422_175404](https://user-images.githubusercontent.com/6137838/203835287-18e3a3cc-f0c0-4062-8f0b-7fccf1c22c73.jpg)

**Comment by Tercioo** [comment]
First, remove your memory counter (right side of the latency) this 
causes small freezes on your game play.

Unfortunately the bug error lines passed isn't enough for the team get 
into a fix.
Try reinstalling all your addons.

------ Original Message ------
From: "Piotr" ***@***.***>
To: "Tercioo/Details-Framework" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 24-Nov-22 1:54:52 PM
Subject: [Tercioo/Details-Framework] Errors 10.0.2 Evoker (Issue #10)

**Comment by Mithras2801** [comment]
I installed this addon yesterday. All add-ons are reinstalled (2 days ago) and are now all in Alpha.

**Comment by Mithras2801** [comment]
![WoWScrnShot_112422_182044](https://user-images.githubusercontent.com/6137838/203839252-a98ffe30-87df-4aef-8c42-b775a441f096.jpg)

On my mage see this errors. I refresh memory
