### ISSUE TITLE
Lua Error after update version

### ISSUE THREAD

**Issue by Mithras2801** [Tercioo/Details-Framework#12]
57x LibDFramework-1.0/icon.lua:52: attempt to index local 'newIconFrame' (a nil value)
[string "@LibDFramework-1.0/icon.lua"]:52: in function `GetIcon'
[string "@LibDFramework-1.0/icon.lua"]:120: in function `SetIcon'
[string "@Plater/Plater_Auras.lua"]:1786: in function `AddExtraIcon'
[string "@Plater/Plater_Auras.lua"]:2079: in function `UpdateAuras_Automatic'
[string "@Plater/Plater.lua"]:6686: in function <Plater/Plater.lua:6532>

Locals:
Skipped (In Encounter)

**Comment by Tercioo** [comment]
thanks for reporting!

**Comment by cont1nuity** [comment]
This is due to the refactoring in DF I assume?
Edit: yes, appears so. Missing a return apparently :)

**Comment by Tercioo** [comment]
it is from the removal of IconRowFrame from panel.lua to icon.lua
got a new DF version sent 435
Edit: yes, moved the icon creation to a separate function in case of wanting just an icon from there.
