### ISSUE TITLE
10.2 PTR error

### ISSUE THREAD

**Issue by jisamcom** [Tercioo/Details-Framework#14]
217x Details/Libs/DF/unitframe.lua:311: Division by zero
[string "@Details/Libs/DF/unitframe.lua"]:311: in function `UpdateHealPrediction'
[string "@Details/Libs/DF/unitframe.lua"]:400: in function `PLAYER_ENTERING_WORLD'
[string "@Details/Libs/DF/unitframe.lua"]:218: in function `SetUnit'
[string "@Details/Libs/DF/unitframe.lua"]:2167: in function `SetUnit'
[string "@Plater/Plater.lua"]:4111: in function `func'
[string "@Plater/Plater.lua"]:4614: in function <Plater/Plater.lua:4610>

Locals:
self = NamePlate22PlaterUnitFrameHealthBar {
 ExecuteGlowDown = Texture {
 }
 OnTick = <function> defined @Details/Libs/DF/unitframe.lua:265
 isNamePlate = true
 GetTexCoord = <function> defined @Details/Libs/DF/mixins.lua:1076
 incomingHealIndicator = Texture {
 }
 SetTexCoord = <function> defined @Details/Libs/DF/mixins.lua:1071
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 actorLevel = FontString {
 }
 SetUnit = <function> defined @Details/Libs/DF/unitframe.lua:172
 unitName = FontString {
 }
 UNIT_MAXHEALTH = <function> defined @Details/Libs/DF/unitframe.lua:408
 ExecuteRangeBar = Texture {
 }
 SetHook = <function> defined @Details/Libs/DF/mixins.lua:383
 barTexture = Texture {
 }
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 SetAlphaTo = <function> defined @Plater/Plater.lua:9151
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 SetBorderTexture = <function> defined @Details/Libs/DF/mixins.lua:1164
 0 = <userdata>
 barTextureMask = MaskTexture {
 }
 HookList = <table> {
 }
 DetailsRealTime = FontString {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 unit = "nameplate1"
 SetVertexColor = <function> defined @Details/Libs/DF/mixins.lua:1054
 SetDesaturated = <function> defined @Details/Libs/DF/mixins.lua:1042
 GetBorderColor = <function> defined @Details/Libs/DF/mixins.lua:1212
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 IsDesaturated = <function> defined @Details/Libs/DF/mixins.lua:1050
 GetColor = <function> defined @Details/Libs/DF/mixins.lua:1085
 shieldIndicator = Texture {
 }
 barBorderTextureForMask = Texture {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 DetailsRealTimeFromPlayer = FontString {
 }
 customborder = Frame {
 }
 AddMaskTexture = <function> defined @Details/Libs/DF/mixins.lua:1117
 IsAnimating = false
 GetBorderTexture = <function> defined @Details/Libs/DF/mixins.lua:1180
 CurrentHealthMax = 0
 UNIT_HEAL_PREDICTION = <function> defined @Details/Libs/DF/unitframe.lua:419
 PixelSnapDisabled = true
 HealthBarEvents = <table> {
 }
 CreateTextureMask = <function> defined @Details/Libs/DF/mixins.lua:1128
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 displayedUnit = "nameplate1"
 SetColor = <function> defined @Details/Libs/DF/mixins.lua:1080
 WidgetType = "healthBar"
 R = 0.200000
 SetDesaturation = <function> defined @Details/Libs/DF/mixins.lua:1046
 G = 0.576471
 PlateFrame = NamePlate22 {
 }
 ExtraRaidMark = Texture {
 }
 GetMaskTexture = <function> defined @Details/Libs/DF/mixins.lua:1096
 GetTexture = <function> defined @Details/Libs/DF/mixins.lua:1038
 B = 0.498039
 FrameOverlay = NamePlate22PlaterUnitFrameHealthBarOverlayFrame {
 }
 Settings = <table> {
 }
 SetMaskAtlas = <function> defined @Details/Libs/DF/mixins.lua:1103
 ExecuteGlowUp = Texture {
 }
 background = Texture {
 }
 A = 1
 GetMaskAtlas = <function> defined @Details/Libs/DF/mixins.lua:1110
 oldHealth = 0
 dversion = 468
 SetMaskTexture = <function> defined @Details/Libs/DF/mixins.lua:1089
 FadeAnimation = AnimationGroup {
 }
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @Details/Libs/DF/unitframe.lua:431
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 currentHealthMax = 0
 CurrentHealth = 0
 UNIT_HEALTH = <function> defined @Details/Libs/DF/unitframe.lua:403
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 ExecuteRangeHealthCutOff = Texture {
 }
 RunH

**Comment by cont1nuity** [comment]
should be fixed with f24afd0
