### ISSUE TITLE
Lua errors on 9.0.1

### ISSUE THREAD

**Issue by Vashidu** [Tercioo/Details-Framework#3]
Message: Interface\AddOns\Details\Libs\DF\cooltip.lua:169: attempt to call method 'SetBackdrop' (a nil value)
Time: Wed Oct 14 12:58:26 2020
Count: 1
Stack: Interface\AddOns\Details\Libs\DF\cooltip.lua:169: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\Details\Libs\DF\cooltip.lua"]:169: in function `build_main_frame'
[string "@Interface\AddOns\Details\Libs\DF\cooltip.lua"]:290: in function `CreateCoolTip'
[string "@Interface\AddOns\Details\Libs\DF\cooltip.lua"]:3413: in main chunk

Locals: self = GameCooltipFrame1 {
 0 = <userdata>
 FlashAnimation = <unnamed> {
 }
 Stop = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:658
 SetBorderColor = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2859
 SetLayerVisibility = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2871
 Borders = <table> {
 }
 SetBorderAlpha = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2843
 Flash = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:663
}
(*temporary) = nil
(*temporary) = GameCooltipFrame1 {
 0 = <userdata>
 FlashAnimation = <unnamed> {
 }
 Stop = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:658
 SetBorderColor = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2859
 SetLayerVisibility = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2871
 Borders = <table> {
 }
 SetBorderAlpha = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2843
 Flash = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:663
}
(*temporary) = <table> {
 bgFile = "Interface\DialogFrame\UI-DialogBox-Background-Dark"
 tileSize = 16
 edgeFile = "Interface\Buttons\WHITE8X8"
 tile = true
 edgeSize = 1
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
DF = <table> {
 DropDownCounter = 957972
 ClassCache = <table> {
 }
 GetAsianNumberSymbols = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:419
 CreateAnts = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2802
 NewLabel = <function> defined @Interface\AddOns\Details\Libs\DF\label.lua:275
 PanelCounter = 957972
 PictureNameCounter = 957972
 Mixin = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2349
 ClientLanguage = "enUS"
 SetHook = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2221
 GetCurrentSpec = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:3221
 CheckPoints = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:718
 GetRangeValue = <function> defined @Interface\AddOns\Details\Libs\DF\math.lua:57
 GetCooldownInfo = <function> defined @Interface\AddOns\Details\Libs\DF\spells.lua:785
 ScheduleTimer = <function> defined @Interface\AddOns\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 NewTextEntry = <function> defined @Interface\AddOns\Details\Libs\DF\textentry.lua:561
 EncodeString = <function> defined @Interface\AddOns\Details\Libs\DF\textentry.lua:1268
 SortOrder3R = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:641
 Msg = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:614
 PrintVersion = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:145
 CreateScrollBar = <function> defined @Interface\AddOns\Details\Libs\DF\scrollbar.lua:7
 CreateGlowOverlay = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2757
 UnitGroupRolesAssigned = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:58
 ShowTutorialAlertFrame = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:1816
 CooldownsExternals = <table> {
 }
 GetSpecializationRole = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:94
 SpecListByClass = <table> {
 }
 FRAMELEVEL_BACKGROUND = 150
 RunHooksForWidget = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:2203
 IntegerToTimer = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:494
 SortOrder1 = <function> defined @Interface\AddOns\Details\Libs\DF\fw.lua:626
 GetDefaultColorList = <func

**Comment by cont1nuity** [comment]
Please get me your Details version. Seems like you're running an outdated one.

**Comment by cont1nuity** [comment]
No response and assumed outdated Details version. DF has not been updated separately here yet. Details carries latest version atm.
